
    create table autenticazione (
        password varchar(255),
        user_id varchar(255) not null,
        primary key (user_id)
    );

    create table carrello (
        data_ultimo_agg date,
        id_carrello integer generated by default as identity,
        user_id integer unique,
        primary key (id_carrello)
    );

    create table categorie (
        id_categoria integer generated by default as identity,
        nome varchar(255),
        primary key (id_categoria)
    );

    create table indirizzi (
        id_indirizzo integer generated by default as identity,
        is_predefinito boolean,
        user_id integer,
        cap varchar(255),
        citta varchar(255),
        tipo varchar(255),
        via varchar(255),
        primary key (id_indirizzo)
    );

    create table messaggi_sistema (
        lang varchar(4) not null,
        code varchar(20) not null,
        messagio varchar(255),
        primary key (lang, code)
    );

    create table metodo_pagamento (
        id_metodo integer generated by default as identity,
        is_predefinito boolean,
        user_id integer,
        dettagli varchar(255),
        tipo varchar(255),
        primary key (id_metodo)
    );

    create table ordini (
        data date,
        id_ordine integer generated by default as identity,
        totale float4,
        user_id integer,
        primary key (id_ordine)
    );

    create table pagamenti (
        data_pagamento date,
        id_metodo integer,
        id_ordine integer unique,
        id_pagamento integer generated by default as identity,
        importo float4,
        stato varchar(255),
        transazione_id varchar(255),
        primary key (id_pagamento)
    );

    create table prodotti (
        categoria integer,
        id_prodotto integer generated by default as identity,
        prezzo float4,
        quantita_disponibile integer,
        user_id integer,
        descrizione varchar(255),
        nome varchar(255),
        primary key (id_prodotto)
    );

    create table prodotti_carrello (
        id_carrello integer,
        id_prodotto integer,
        id_riga integer generated by default as identity,
        prezzo_snapshot float4,
        quantita integer,
        primary key (id_riga)
    );

    create table prodotti_ordine (
        id_item integer generated by default as identity,
        id_ordine integer,
        id_prodotto integer,
        prezzo float4,
        quantita integer,
        primary key (id_item)
    );

    create table ricevuta (
        data_emissione date,
        id_fattura integer generated by default as identity,
        id_ordine integer unique,
        imponibile float4,
        iva float4,
        totale float4,
        numero_fattura varchar(255),
        primary key (id_fattura)
    );

    create table ruoli (
        ruolo varchar(255) not null,
        primary key (ruolo)
    );

    create table sconti (
        data_fine date,
        data_inizio date,
        id_prodotto integer,
        id_sconto integer generated by default as identity,
        valore float4,
        tipo varchar(255),
        primary key (id_sconto)
    );

    create table status_ordine (
        stato varchar(255) not null,
        primary key (stato)
    );

    create table users (
        id_user integer generated by default as identity,
        cognome varchar(255),
        email varchar(255) not null unique,
        indirizzo varchar(255),
        nome varchar(255),
        ruolo varchar(255),
        telefono varchar(255),
        primary key (id_user)
    );

    alter table if exists autenticazione 
       add constraint FKpy1kj4dfd284wkrcai8httg07 
       foreign key (user_id) 
       references users;

    alter table if exists carrello 
       add constraint FK8wocb69w6jyqefu7etmxgni2p 
       foreign key (user_id) 
       references users;

    alter table if exists indirizzi 
       add constraint FKplpq215m028r1n3bo6n2hkb2s 
       foreign key (user_id) 
       references users;

    alter table if exists metodo_pagamento 
       add constraint FKkimw751gpi5ktca1qj9x33dit 
       foreign key (user_id) 
       references users;

    alter table if exists ordini 
       add constraint FK6odl1p603s8jmass6j0h3bhna 
       foreign key (user_id) 
       references users;

    alter table if exists pagamenti 
       add constraint FK6qxunpjghhj5j09spov7i8vuf 
       foreign key (id_metodo) 
       references metodo_pagamento;

    alter table if exists pagamenti 
       add constraint FKb19bn6ntprd4pcu61w9fpyqin 
       foreign key (id_ordine) 
       references ordini;

    alter table if exists prodotti 
       add constraint FKbtowcuwota1u5q8828gyrhxnk 
       foreign key (categoria) 
       references categorie;

    alter table if exists prodotti 
       add constraint FK4048s4fgw4f6m3qphnjv5jloe 
       foreign key (user_id) 
       references users;

    alter table if exists prodotti_carrello 
       add constraint FKgv1pg75xggqeq3s0xmvy9k9lg 
       foreign key (id_carrello) 
       references carrello;

    alter table if exists prodotti_carrello 
       add constraint FK3bqrhc1ybxv7a3ioweqoo2chm 
       foreign key (id_prodotto) 
       references prodotti;

    alter table if exists prodotti_ordine 
       add constraint FKrbg6wjfkm0ahqtiy3vuivkfaf 
       foreign key (id_ordine) 
       references ordini;

    alter table if exists prodotti_ordine 
       add constraint FK90duas5hnh3p3kb88dg9oswa0 
       foreign key (id_prodotto) 
       references prodotti;

    alter table if exists ricevuta 
       add constraint FK3dsdedap0rkk2ptltsi5fxvt5 
       foreign key (id_ordine) 
       references ordini;

    alter table if exists sconti 
       add constraint FK8wq2bkcqu3wvmsfw4fatf6xap 
       foreign key (id_prodotto) 
       references prodotti;

    alter table if exists users 
       add constraint FK7vgts5e6ne7mf7uw9nrd8kpc3 
       foreign key (ruolo) 
       references ruoli;
