
    create table autenticazione (
        password varchar(255) not null,
        user varchar(255) not null,
        primary key (user)
    );

    create table carrello (
        data_ultimo_agg date,
        id_carrello integer generated by default as identity,
        user integer unique,
        primary key (id_carrello)
    );

    create table categorie (
        id_categoria integer generated by default as identity,
        categoria varchar(255) not null,
        primary key (id_categoria)
    );

    create table indirizzi (
        id_indirizzo integer generated by default as identity,
        predefinito boolean,
        user integer,
        cap varchar(255) not null,
        citta varchar(255) not null,
        via varchar(255) not null,
        primary key (id_indirizzo)
    );

    create table messaggi_sistema (
        lang varchar(4) not null,
        code varchar(20) not null,
        messagio varchar(255),
        primary key (lang, code)
    );

    create table metodo_pagamento (
        id_metodo integer generated by default as identity,
        is_predefinito boolean,
        user integer,
        dettagli varchar(255) not null,
        tipo varchar(255) not null,
        primary key (id_metodo)
    );

    create table ordini (
        data date not null,
        id_ordine integer generated by default as identity,
        indirizzo_fatturazione integer unique,
        indirizzo_spedizione integer unique,
        totale float4 not null,
        user integer,
        stato_ordine varchar(255),
        primary key (id_ordine)
    );

    create table pagamenti (
        data_pagamento date not null,
        id_pagamento integer generated by default as identity,
        importo float4 not null,
        metodo_pagamento integer,
        ordine integer unique,
        stato_pagamento varchar(255),
        transazione_id varchar(255),
        primary key (id_pagamento)
    );

    create table prodotti (
        categoria integer,
        id_prodotto integer generated by default as identity,
        prezzo float4 not null,
        quantita_disponibile int default 0 not null,
        user integer,
        descrizione varchar(255) not null,
        primary key (id_prodotto)
    );

    create table prodotti_carrello (
        carrello integer,
        id_riga integer generated by default as identity,
        prezzo float4 not null,
        prodotto integer,
        quantita integer not null,
        primary key (id_riga)
    );

    create table prodotti_ordine (
        id_item integer generated by default as identity,
        ordine integer,
        prezzo float4 not null,
        prodotto integer,
        quantita integer not null,
        primary key (id_item)
    );

    create table ricevuta (
        data_emissione date not null,
        id_fattura integer generated by default as identity,
        imponibile float4 not null,
        iva float4 not null,
        ordine integer unique,
        totale float4 not null,
        numero_fattura varchar(255) not null,
        primary key (id_fattura)
    );

    create table ruoli (
        ruolo varchar(255) not null,
        primary key (ruolo)
    );

    create table sconti (
        data_fine date not null,
        data_inizio date not null,
        id_sconto integer generated by default as identity,
        prodotto integer,
        valore float4 not null,
        primary key (id_sconto)
    );

    create table stato_ordine (
        stato varchar(255) not null,
        primary key (stato)
    );

    create table stato_pagamenti (
        stato varchar(255) not null,
        primary key (stato)
    );

    create table users (
        id_user integer generated by default as identity,
        cognome varchar(255) not null,
        email varchar(255) not null unique,
        nome varchar(255) not null,
        ruolo varchar(255),
        telefono varchar(255) not null,
        primary key (id_user)
    );

    alter table if exists autenticazione 
       add constraint FKhp9xykeporddr021barv2u5y6 
       foreign key (user) 
       references users;

    alter table if exists carrello 
       add constraint FK4lus6odvncyml62i4k7wakij6 
       foreign key (user) 
       references users;

    alter table if exists indirizzi 
       add constraint FKsn1d63u2l9aospedj6wsojpps 
       foreign key (user) 
       references users;

    alter table if exists metodo_pagamento 
       add constraint FKkfhintbbf2ysrb8gjb9wap6ga 
       foreign key (user) 
       references users;

    alter table if exists ordini 
       add constraint FKj77333p7l9ognbsgl5q7sroux 
       foreign key (indirizzo_fatturazione) 
       references indirizzi;

    alter table if exists ordini 
       add constraint FKn9pthby85h3scynafely8xjxj 
       foreign key (indirizzo_spedizione) 
       references indirizzi;

    alter table if exists ordini 
       add constraint FKp9v03irbus4f4l5urhtyu8rwe 
       foreign key (stato_ordine) 
       references stato_ordine;

    alter table if exists ordini 
       add constraint FK8f7bjdq6rbfl3g290697eyilx 
       foreign key (user) 
       references users;

    alter table if exists pagamenti 
       add constraint FKaj1gphc6v5nsuetqyf5ykc9d9 
       foreign key (metodo_pagamento) 
       references metodo_pagamento;

    alter table if exists pagamenti 
       add constraint FKf2x11hvonh4h2qu4f4oloiv4y 
       foreign key (ordine) 
       references ordini;

    alter table if exists pagamenti 
       add constraint FKq77eli5kv3okbvr7p1smf7v28 
       foreign key (stato_pagamento) 
       references stato_pagamenti;

    alter table if exists prodotti 
       add constraint FKbtowcuwota1u5q8828gyrhxnk 
       foreign key (categoria) 
       references categorie;

    alter table if exists prodotti 
       add constraint FK3gc52tocic1v0wpn9wts41tv4 
       foreign key (user) 
       references users;

    alter table if exists prodotti_carrello 
       add constraint FKculjnbh3efj9cqtjwhrf57vyk 
       foreign key (carrello) 
       references carrello;

    alter table if exists prodotti_carrello 
       add constraint FK7j387fc10rblygr2p6ufv30jb 
       foreign key (prodotto) 
       references prodotti;

    alter table if exists prodotti_ordine 
       add constraint FKoryut1a41bxv1hvmqxv3few9q 
       foreign key (ordine) 
       references ordini;

    alter table if exists prodotti_ordine 
       add constraint FKgb812bitx3s292cna1852ykjg 
       foreign key (prodotto) 
       references prodotti;

    alter table if exists ricevuta 
       add constraint FKnob6wi8vsui2745e42pkabc9c 
       foreign key (ordine) 
       references ordini;

    alter table if exists sconti 
       add constraint FKsm4cljgbr05sljbp6l9qw7ray 
       foreign key (prodotto) 
       references prodotti;

    alter table if exists users 
       add constraint FK7vgts5e6ne7mf7uw9nrd8kpc3 
       foreign key (ruolo) 
       references ruoli;
